name        : dosfstools
version     : 3.0.28
release     : 7
source      :
    - https://github.com/dosfstools/dosfstools/archive/v3.0.28.tar.gz : bfbbfbe0c0da70d60332e3fb830a5afd7351a424c0e4b3c025db5bfe9e6efc36
homepage    : http://www.daniel-baumann.ch/software/dosfstools/
license     : GPL-2.0+
summary     : dosfstools (Tools for making and checking MS-DOS Fat filesystems)
component   : system.utils
description : |
    dosfstools are tools for making and checking MS-DOS Fat filesystems.  It includes tools for vfat formats.
build      : |
    %make
install    : |
    %make_install PREFIX=/usr BINDIR=/sbin SBINDIR=/sbin
