name       : dosfstools
version    : 4.1
release    : 10
source     :
    - https://github.com/dosfstools/dosfstools/archive/v4.1.tar.gz : 8ff9c2dcc01551fe9de8888cb41eb1051fd58bdf1ab3a93d3d88916f0a4ffd1b
license    : GPL-3.0-or-later
summary    : dosfstools (Tools for making and checking MS-DOS Fat filesystems)
component  : system.utils
description: |
    dosfstools are tools for making and checking MS-DOS Fat filesystems.  It includes tools for vfat formats.
builddeps  :
    # For tests. dosfstools requires xxd
        - vim
setup      : |
    %reconfigure --enable-compat-symlinks
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
