name       : dosfstools
version    : 4.0
release    : 8
source     :
    - https://github.com/dosfstools/dosfstools/releases/download/v4.0/dosfstools-4.0.tar.xz : 9037738953559d1efe04fc5408b6846216cc0138f7f9d32de80b6ec3c35e7daf
homepage   : http://www.daniel-baumann.ch/software/dosfstools/
license    : GPL-2.0+
summary    : dosfstools (Tools for making and checking MS-DOS Fat filesystems)
component  : system.utils
description: |
    dosfstools are tools for making and checking MS-DOS Fat filesystems.  It includes tools for vfat formats.
setup      : |
    unset LD_AS_NEEDED
    %configure --enable-compat-symlinks
build      : |
    unset LD_AS_NEEDED
    %make -j1
install    : |
    unset LD_AS_NEEDED
    %make_install
